/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: (typeof import('vue'))['EffectScope'];
  const ElButton: (typeof import('element-plus'))['ElButton'];
  const ElDialog: (typeof import('element-plus'))['ElDialog'];
  const ElDrawer: (typeof import('element-plus'))['ElDrawer'];
  const ElForm: (typeof import('element-plus'))['ElForm'];
  const ElFormItem: (typeof import('element-plus'))['ElFormItem'];
  const ElInput: (typeof import('element-plus'))['ElInput'];
  const ElNotification: (typeof import('element-plus'))['ElNotification'];
  const ElOption: (typeof import('element-plus'))['ElOption'];
  const ElPopover: (typeof import('element-plus'))['ElPopover'];
  const ElScrollbar: (typeof import('element-plus'))['ElScrollbar'];
  const ElSelect: (typeof import('element-plus'))['ElSelect'];
  const ElSwitch: (typeof import('element-plus'))['ElSwitch'];
  const ElTooltip: (typeof import('element-plus'))['ElTooltip'];
  const ElementPlus: (typeof import('element-plus'))['default'];
  const VueQueryPlugin: (typeof import('@tanstack/vue-query'))['VueQueryPlugin'];
  const computed: (typeof import('vue'))['computed'];
  const createApp: (typeof import('vue'))['createApp'];
  const createI18n: (typeof import('vue-i18n'))['createI18n'];
  const createPinia: (typeof import('pinia'))['createPinia'];
  const createRouter: (typeof import('vue-router'))['createRouter'];
  const createWebHistory: (typeof import('vue-router'))['createWebHistory'];
  const customRef: (typeof import('vue'))['customRef'];
  const defineAsyncComponent: (typeof import('vue'))['defineAsyncComponent'];
  const defineComponent: (typeof import('vue'))['defineComponent'];
  const defineStore: (typeof import('pinia'))['defineStore'];
  const effectScope: (typeof import('vue'))['effectScope'];
  const forEach: (typeof import('lodash-es'))['forEach'];
  const get: (typeof import('lodash-es'))['get'];
  const getCurrentInstance: (typeof import('vue'))['getCurrentInstance'];
  const getCurrentScope: (typeof import('vue'))['getCurrentScope'];
  const h: (typeof import('vue'))['h'];
  const head: (typeof import('lodash-es'))['head'];
  const inject: (typeof import('vue'))['inject'];
  const isArray: (typeof import('lodash-es'))['isArray'];
  const isProxy: (typeof import('vue'))['isProxy'];
  const isReactive: (typeof import('vue'))['isReactive'];
  const isReadonly: (typeof import('vue'))['isReadonly'];
  const isRef: (typeof import('vue'))['isRef'];
  const join: (typeof import('lodash-es'))['join'];
  const markRaw: (typeof import('vue'))['markRaw'];
  const nextTick: (typeof import('vue'))['nextTick'];
  const noop: (typeof import('lodash-es'))['noop'];
  const omit: (typeof import('lodash-es'))['omit'];
  const onActivated: (typeof import('vue'))['onActivated'];
  const onBeforeMount: (typeof import('vue'))['onBeforeMount'];
  const onBeforeUnmount: (typeof import('vue'))['onBeforeUnmount'];
  const onBeforeUpdate: (typeof import('vue'))['onBeforeUpdate'];
  const onDeactivated: (typeof import('vue'))['onDeactivated'];
  const onErrorCaptured: (typeof import('vue'))['onErrorCaptured'];
  const onMounted: (typeof import('vue'))['onMounted'];
  const onRenderTracked: (typeof import('vue'))['onRenderTracked'];
  const onRenderTriggered: (typeof import('vue'))['onRenderTriggered'];
  const onScopeDispose: (typeof import('vue'))['onScopeDispose'];
  const onServerPrefetch: (typeof import('vue'))['onServerPrefetch'];
  const onUnmounted: (typeof import('vue'))['onUnmounted'];
  const onUpdated: (typeof import('vue'))['onUpdated'];
  const onWatcherCleanup: (typeof import('vue'))['onWatcherCleanup'];
  const provide: (typeof import('vue'))['provide'];
  const reactive: (typeof import('vue'))['reactive'];
  const readonly: (typeof import('vue'))['readonly'];
  const ref: (typeof import('vue'))['ref'];
  const resolveComponent: (typeof import('vue'))['resolveComponent'];
  const shallowReactive: (typeof import('vue'))['shallowReactive'];
  const shallowReadonly: (typeof import('vue'))['shallowReadonly'];
  const shallowRef: (typeof import('vue'))['shallowRef'];
  const toRaw: (typeof import('vue'))['toRaw'];
  const toRef: (typeof import('vue'))['toRef'];
  const toRefs: (typeof import('vue'))['toRefs'];
  const toValue: (typeof import('vue'))['toValue'];
  const triggerRef: (typeof import('vue'))['triggerRef'];
  const unref: (typeof import('vue'))['unref'];
  const useAttrs: (typeof import('vue'))['useAttrs'];
  const useCssModule: (typeof import('vue'))['useCssModule'];
  const useCssVars: (typeof import('vue'))['useCssVars'];
  const useI18n: (typeof import('vue-i18n'))['useI18n'];
  const useId: (typeof import('vue'))['useId'];
  const useModel: (typeof import('vue'))['useModel'];
  const useMutation: (typeof import('@tanstack/vue-query'))['useMutation'];
  const useQuery: (typeof import('@tanstack/vue-query'))['useQuery'];
  const useQueryClient: (typeof import('@tanstack/vue-query'))['useQueryClient'];
  const useRoute: (typeof import('vue-router'))['useRoute'];
  const useRouter: (typeof import('vue-router'))['useRouter'];
  const useSlots: (typeof import('vue'))['useSlots'];
  const useTemplateRef: (typeof import('vue'))['useTemplateRef'];
  const watch: (typeof import('vue'))['watch'];
  const watchEffect: (typeof import('vue'))['watchEffect'];
  const watchPostEffect: (typeof import('vue'))['watchPostEffect'];
  const watchSyncEffect: (typeof import('vue'))['watchSyncEffect'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    ComponentPublicInstance,
    ComputedRef,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    VNode,
    WritableComputedRef,
  } from 'vue';
  import('vue');
  // @ts-ignore
  export type {
    RouteRecordRaw,
    RouteLocationNormalized,
    NavigationGuardNext,
  } from 'vue-router';
  import('vue-router');
  // @ts-ignore
  export type { FormRules, FormInstance } from 'element-plus';
  import('element-plus');
  // @ts-ignore
  export type {
    InitialDataFunction,
    QueryClient,
    VueQueryPluginOptions,
  } from '@tanstack/vue-query';
  import('@tanstack/vue-query');
}
