name: build-and-test CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
       
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run linting
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

       - name: Build the project
        run: pnpm run build --if-present
      
