name: Build and Test CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.4

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint

      # - name: Run tests // TODO: Later
      #   run: pnpm test

      - name: Build the project
        run: pnpm build --if-present
